/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API health status
         * @description Returns the current health status of the API service along with a status message
         */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lottery games
         * @description List lottery games
         */
        get: operations["LotteryController_getGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lottery payout summaries
         * @description List of payout summaries for all lottery games
         */
        get: operations["LotteryController_getPayoutSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get combined lottery dashboard data
         * @description Retrieves combined data about lottery games including game details and payout information
         */
        get: operations["LotteryController_getDashboardData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/process-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LotteryController_processData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Game: {
            /** @example 1 */
            id: number;
            /** @example Mega Ball 500 */
            name: string;
            /** @example 5.00 */
            ticket_price: number;
            /** @example 100000.00 */
            initial_jackpot: number;
            /** @example 0 */
            total_tickets_sold: number;
            /** @example 100000.00 */
            current_jackpot: number;
        };
        PayoutSummary: {
            /** @example 1 */
            id: number;
            /** @example Mega Ball 500 */
            game_name: string;
            /** @example 100000.0 */
            total_prizes_paid: number;
            /**
             * Format: date-time
             * @example 2025-04-30
             */
            last_payout_date: string;
        };
        DashboardData: {
            /** @example 1 */
            id: number;
            /** @example Mega Ball 500 */
            name: string;
            /** @example 5.00 */
            ticket_price: number;
            /** @example 100000.00 */
            initial_jackpot: number;
            /** @example 0 */
            total_tickets_sold: number;
            /** @example 100000.00 */
            current_jackpot: number;
            /** @example 50000.00 */
            total_prizes_paid: number;
            /** @example 2025-04-30 */
            last_payout_date: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "message": "Server is running! Check /api/dashboard-data for lottery data."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    LotteryController_getGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of lottery games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
        };
    };
    LotteryController_getPayoutSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of payout summary for lottery games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutSummary"][];
                };
            };
        };
    };
    LotteryController_getDashboardData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined lottery games and payout data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardData"][];
                };
            };
        };
    };
    LotteryController_processData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
